package frostscape.world;

import arc.func.Prov;
import arc.struct.Seq;
import frostscape.type.upgrade.Upgrade;
import frostscape.world.blocks.drawers.UpgradeDrawer;
import frostscape.world.upgrades.UpgradeEntry;
import mindustry.entities.bullet.SapBulletType;
import mindustry.gen.Building;
import mindustry.world.Block;
import mindustry.world.draw.DrawBlock;

public class FrostscapeBlock extends Block implements UpgradesBlock{
    public FrostscapeBlock(String name) {
        super(name);
        this.update = true;
        this.solid = true;
    }


    //Aplicable upgrades, autogenerated
    public final Seq<Upgrade> upgrades = new Seq<>();

    public Seq<UpgradeEntry> entries = new Seq<>();

    @Override
    public Seq<UpgradeEntry> entries() {
        return entries;
    }

    @Override
    public void load() {
        super.load();
        entries.each(entry -> {
            entry.initialiseDeltas();
            upgrades.add(entry.upgrade);
        });
    }

    @Override
    public boolean isVisible() {
        return super.isVisible();
    }

    @Override
    public Seq<Upgrade> upgrades(){
        return upgrades;
    }

    @Override
    public Seq<UpgradeDrawer> drawers() {
        return null;
    }
}
